---
- hosts: leaf1, leaf3
  name: Add VLAN
  tasks:
  - name: Add VLAN 10
    arista.eos.eos_vlans:
      config:
      - vlan_id: 10
        state: active
      state: deleted
  - name: Save Configuration
    arista.eos.eos_command:
      commands:
      - copy run start

